### ISSUE TITLE
The build is broken due to `memset(this`

### ISSUE THREAD

**Issue by alzpublic** [WAVM/WAVM#216]
There is a trivial problem that breaks build with the recent version of gcc

```
... wavm/Include/WAVM/IR/Value.h:39:50: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct WAVM::IR::UntaggedValue’; use assignment or value-initialization instead [-Werror=class-memaccess]
```

Probably need to add `(void*)` before `this`.
```
UntaggedValue() { memset(this, 0, sizeof(*this)); }
```

**Comment by AndrewScheidecker** [comment]
Thanks, I'll probably do `memset(bytes, 0, sizeof(bytes))`. I see there's also an error due to `I128` missing a copy constructor.

I'll try to add a CI job that build with GCC 9.2 to catch stuff like this.
